accounts/urls.py
from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required
from accounts.views import MyProfileView, MyProfileCreateView, ProfileView, MyProfileEditView, RegistrationView, ThankyouView

urlpatterns = patterns('',
    url(r'login/$',
        'accounts.views.login',
        { 'template_name': 'accounts/login.html', },
        name='accounts_login'
    ),
    url(r'logout/$',
        'django.contrib.auth.views.logout',
        { 'template_name': 'accounts/logged_out.html', },
        name='accounts_logout'
    ),
    url(r'register/$',
        RegistrationView.as_view(),
        name='accounts_register'
    ),
    url(r'thankyou/$',
        ThankyouView.as_view(),
        name='accounts_register_thankyou'
    ),

    url(r'profile/(?P<pk>\d+)/$',
        ProfileView.as_view(),
        name='accounts_profile'
    ),
    url(r'profile/$',
        login_required(MyProfileView.as_view()),
        name='accounts_my_profile'
    ),
    url(r'profile/new/$',
        login_required(MyProfileCreateView.as_view()),
        name='accounts_my_profile_new'
    ),
    url(r'profile/edit/$',
        login_required(MyProfileEditView.as_view()),
        name='accounts_my_profile_edit'
    ),
)

urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from registration.forms import RegistrationFormUniqueEmail
from registration.views import register

admin.autodiscover()

urlpatterns = patterns('',
    # Utility urls
    # url(r'^comments/', include('django.contrib.comments.urls')),

    # Examples:
    # url(r'^$', 'tenniswall.views.home', name='home'),
    # url(r'^tenniswall/', include('tenniswall.foo.urls')),
    url(r'^$', include('welcome.urls')),

    url(r'^accounts/register/$',
        register,
        {'form_class': RegistrationFormUniqueEmail,},
        'registration_register',
    ),
    url(r'^accounts/', include('registration.urls')),

    url(r'^profiles/', include('profiles.urls')),

    url(r'^facebook/', include('django_facebook.urls')),

    url(r'^walls/', include('walls.urls')),
    url(r'^world/', include('world.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

# Static files
if settings.SERVE_STATIC:
    # Static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

    # Media
    media_url = settings.MEDIA_URL
    if media_url[0] == '/':
        media_url = media_url[1:]
    if media_url[-1] != '/':
        media_url += '/'
    urlpatterns += patterns('django.views.static',
        url(r'^%(media_url)s(?P<path>.*)$' % {'media_url': media_url},
            'serve',
            {'document_root': settings.MEDIA_ROOT + '/'}
        )
    )

accounts/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save
from django.utils.translation import ugettext as _

class UserProfile(models.Model):
    SEX_CHOICES = (
        (True, _('Male')),
        (False, _('Female')),
    )

    user = models.ForeignKey(User, unique=True, editable=False)

    birthday = models.DateField(null=True, blank=True)
    sex = models.NullBooleanField(choices=SEX_CHOICES)

    is_closed = models.BooleanField(default=False, db_index=True)

    updated_at = models.DateTimeField(auto_now=True, editable=False)

    def __unicode__(self):
        if self.user.first_name == "" and self.user.last_name == "":
            return "%s's profile" % unicode(self.user)
        return self.get_name()

    def get_name(self):
        return " ".join([self.user.first_name, self.user.last_name])

    def get_absolute_url(self):
        return reverse('accounts_profile', args=[self.user.pk])

    def can_show(self):
        return not self.is_closed

    def can_edit(self, user):
        return self.user == user

def user_created_handler(sender, instance, created, **kwargs):
    if created:
        instance.userprofile_set.create()

post_save.connect(user_created_handler,
                  sender=User,
                  dispatch_uid="users-profilecreation-signal")

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from accounts.models import UserProfile
from accounts.widgets import CalendarWidget

class NewUserForm(UserCreationForm):
    email = forms.EmailField(label=_('Email'))

    class Meta(UserCreationForm.Meta):
        fields = (
            'username',
            'email',
            'password1',
            'password2',
        )

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email):
            raise forms.ValidationError(
                _('User with the same email is already registered'))
        return email

class UserprofileForm(forms.ModelForm):
    class Meta:
        model = UserProfile

        widgets = {
            'birthday': CalendarWidget
        }

accounts/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.utils.functional import lazy
from django.utils.translation import ugettext as _
from django.views.generic import DetailView, CreateView, UpdateView, TemplateView
from accounts.forms import  UserprofileForm, NewUserForm
from accounts.models import UserProfile

#########
# Views #
#########
def login(request, *args, **kwargs):
    from django.contrib.auth.views import login as auth_login
    if request.user.is_authenticated():
        return redirect('accounts_my_profile')
    return auth_login(request, *args, **kwargs)

class RegistrationView(CreateView):
    model = User
    form_class = NewUserForm
    template_name = 'accounts/user_form.html'
    success_url = lazy(reverse, str)('accounts_register_thankyou')

    def get(self, request, *args, **kwargs):
        return conditional_method(
            request.user.is_authenticated(),
            lambda : redirect('accounts_my_profile'),
            lambda : super(RegistrationView, self).get(request,
                                                       *args, **kwargs)
        )

    def post(self, request, *args, **kwargs):
        return conditional_method(
            request.user.is_authenticated(),
            lambda : redirect('accounts_my_profile'),
            lambda : super(RegistrationView, self).post(request,
                                                        *args, **kwargs)
        )

    def form_valid(self, form):
        username = form.cleaned_data['username']
        self.request.session['registered_user_name'] = username
        messages.success(self.request, _('User is registered'))
        return super(RegistrationView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _('User is not registered'))
        return super(RegistrationView, self).form_invalid(form)

class ThankyouView(TemplateView):
    template_name = 'accounts/thankyou.html'

    def get_context_data(self, **kwargs):
        registered_user_name = self.request.session.get(
            'registered_user_name', False
        )

        try:
            del self.request.session['registered_user_name']
        except KeyError:
            pass

        context = super(ThankyouView, self).get_context_data(**kwargs)
        context['registered_user_name'] = registered_user_name
        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        if context.get('registered_user_name', False):
            return self.render_to_response(context)
        return redirect('root')

class ProfileView(DetailView):
    model = UserProfile

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        return get_object_or_404(UserProfile, user__pk=pk)

    def get(self, request, **kwargs):
        if (request.user.is_authenticated()
            and int(self.kwargs.get('pk')) == request.user.id):
            return redirect('accounts_my_profile')
        return super(ProfileView, self).get(request, **kwargs)

class MyProfileView(DetailView):
    model = UserProfile

    def get_object(self, queryset=None):
        try:
            userprofile = self.request.user.get_profile()
        except UserProfile.DoesNotExist:
            userprofile = None
        return userprofile

    def render_to_response(self, context, **response_kwargs):
        if not self.object:
            return redirect('accounts_my_profile_new')
        return super(MyProfileView, self).render_to_response(context, **response_kwargs)

class MyProfileCreateView(CreateView):
    model = UserProfile
    form_class = UserprofileForm

    def get(self, request, *args, **kwargs):
        if self._check_profile_exists(request.user):
            return redirect('accounts_my_profile')
        return super(MyProfileCreateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if self._check_profile_exists(request.user):
            return redirect('accounts_my_profile')
        return super(MyProfileCreateView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        messages.success(self.request, _('User profile is created'))
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        messages.error(self.request, _('User profile is not created'))
        return super(MyProfileCreateView, self).form_invalid(form)

    def _check_profile_exists(self, user):
        return UserProfile.objects.filter(user=user).exists()

class MyProfileEditView(UpdateView):
    model = UserProfile
    form_class = UserprofileForm

    def get_object(self, queryset=None):
        try:
            userprofile = self.request.user.get_profile()
        except UserProfile.DoesNotExist:
            userprofile = None
        return userprofile

    def form_valid(self, form):
        messages.success(self.request, _('User profile is updated'))
        return super(MyProfileEditView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _('User profile is not updated'))
        return super(MyProfileEditView, self).form_invalid(form)

    def render_to_response(self, context, **response_kwargs):
        if not self.object:
            return redirect('accounts_my_profile_new')
        return super(MyProfileEditView, self).render_to_response(context, **response_kwargs)

#########
# Utils #
#########
def conditional_method(predicate, l1, l2):
    if hasattr(predicate, '__call__'):
        predicate = predicate()
    if predicate:
        return l1()
    return l2()

accounts/templates/accounts/login.html
{% extends 'base_no_auth.html' %}
{% load i18n %}
{% load url from future %}

{% block content %}
  {% if form.errors %}
    <p class="non_field_errors error">
      {% trans "Your username and password didn't match. Please try again." %}
    </p>
  {% endif %}

  <form action="{% url 'auth_login' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />

    <div class="form span-24 last">
      <div class="non_field_errors span-24 last">
        {{ form.non_field_errors }}
      </div>

      {% for field in form %}
        <div class="field span-24 last {% if field.errors %}error{% endif %}">
          {% if field.errors %}
            <div class="input_errors_top align-left span-24 last">
              {{ field.errors }}
            </div>
          {% endif %}
          <div class="label align-right span-24 last">
            {{ field.label_tag }}
          </div>
          <div class="field-info align-left span-24 last">
            {{ field.help_text }}
          </div>
          <div class="input align-left span-24 last">
            {{ field }}
          </div>
        </div>
      {% endfor %}
    
      <div class="field submit span-24 last">
        <input type="submit" value={% trans 'Login' %} />
      </div>
    </div>
  </form>
{% endblock %}

accounts/templates/accounts/thankyou.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block content %}
  <h3>{% trans 'Thank you for registering' %}, {{ registered_user_name }}!</h3>
{% endblock %}

accounts/templates/accounts/user_form.html
{% extends 'base_no_auth.html' %}
{% load i18n %}

{% block content %}
  <form action="." method="post">
    {% csrf_token %}

    <div class="form span-24 last">
      <div class="non_field_errors span-24 last">
        {{ form.non_field_errors }}
      </div>
      {% for field in form %}
        {% if field.is_hidden %}
          {{ field }}
        {% else %}
          <div class="field span-24 last {% if field.errors %}error{% endif %}">
            {% if field.errors %}
              <div class="input_errors_top align-left span-24 last">
                {{ field.errors }}
              </div>
            {% endif %}
            <div class="label align-right span-24 last">
              {{ field.label_tag }}
            </div>
            <div class="field-info align-left span-24 last">
              {{ field.help_text }}
            </div>
            <div class="input align-left span-24 last">
              {{ field }}
            </div>
          </div>
        {% endif %}
      {% endfor %}
      <div class="field submit span-24 last">
        <input type="submit" value={% trans 'Register' %} />
      </div>
    </div>
  </form>
{% endblock %}

accounts/templates/accounts/userprofile_detail.html
{% extends 'accounts/base.html' %}
{% load i18n models %}

{% block content %}
  <div id="profile_detail" class="span-24 last">
    {% ifcan request.user 'edit' object %}
      <div id="object_controls" class="object_controls span-24 last">
        <ul class="menu horizontal">
          <li>
            <a href="{% url accounts_my_profile_edit %}">
              {% trans 'Edit' %}
            </a>
          </li>
          <li>
            <a href="{% url walls_my_list %}">
              {% trans 'My walls' %}
            </a>
          </li>
        </ul>
      </div>
    {% endifcan %}
    
    <div id="profile_info" class="span-10">
      <div class="object_field">
        <div class="object_field_title">{% trans 'Birthday' %}</div>
        {{ object.birthday }}
      </div>
    </div>
    <div id="profile_other" class="span-14 last">
      <div class="object_field">
        <div class="object_field_title">{% trans 'Sex' %}</div>
        {{ object.get_sex_display }}
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/userprofile_form.html
{% extends 'accounts/base.html' %}
{% load i18n %}

{% block content %}
  <form action="." method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
      {% for field in form %}
        <tr class="field {% if field.errors %}error{% endif %}">
          <td class="label">
            {{ field.label_tag }}
          </td>
          <td class="input_errors_inline">
            {{ field.errors }}
          </td>
          <td class="input">
            {{ field }}
          </td>
          <td class="field-info">
            {{ field.help_text }}
          </td>
        </tr>
      {% endfor %}
      <tr>
        <td colspan="4" class="input submit">
          <input type="submit" value={% trans 'Save' %} />
        </td>
      </tr>
    </table>
  </form>
{% endblock %}