urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from registration.forms import RegistrationFormUniqueEmail
from registration.views import register

admin.autodiscover()

urlpatterns = patterns('',
    # Utility urls
    # url(r'^comments/', include('django.contrib.comments.urls')),

    # Examples:
    # url(r'^$', 'tenniswall.views.home', name='home'),
    # url(r'^tenniswall/', include('tenniswall.foo.urls')),
    url(r'^$', include('welcome.urls')),

    url(r'^accounts/register/$',
        register,
        {'form_class': RegistrationFormUniqueEmail,},
        'registration_register',
    ),
    url(r'^accounts/', include('registration.urls')),

    url(r'^profiles/', include('profiles.urls')),

    url(r'^facebook/', include('django_facebook.urls')),

    url(r'^walls/', include('walls.urls')),
    url(r'^world/', include('world.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

# Static files
if settings.SERVE_STATIC:
    # Static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

    # Media
    media_url = settings.MEDIA_URL
    if media_url[0] == '/':
        media_url = media_url[1:]
    if media_url[-1] != '/':
        media_url += '/'
    urlpatterns += patterns('django.views.static',
        url(r'^%(media_url)s(?P<path>.*)$' % {'media_url': media_url},
            'serve',
            {'document_root': settings.MEDIA_ROOT + '/'}
        )
    )

walls/urls.py
from django.conf.urls.defaults import patterns, url
from django.contrib.auth.decorators import login_required
from walls.views import AddWallView, EditWallView,\
    CommentedWallDetailView, DeleteWallView, WallImagesListView,\
    WallImagesDetailView, WallImagesEditView, WallImagesDeleteView,\
    WallImagesAddView, WallImagesListEditView, MyWallsListView

urlpatterns = patterns('',
    url(r'^my/$',
        login_required(MyWallsListView.as_view()),
        name='walls_my_list'
    ),
    url(r'^(?P<pk>\d+)/$',
        CommentedWallDetailView.as_view(),
        name='walls_detail'
    ),
    url(r'^(?P<pk>\d+)/edit/$',
        login_required(EditWallView.as_view()),
        name='walls_edit'
    ),
    url(r'^(?P<pk>\d+)/delete/$',
        login_required(DeleteWallView.as_view()),
        name='walls_delete'
    ),
    url(r'^add/$',
        login_required(AddWallView.as_view()),
        name='walls_add'
    ),

    url(r'^(?P<wall_pk>\d+)/images/$',
        WallImagesListView.as_view(),
        name='walls_images_list'
    ),
    url(r'^(?P<wall_pk>\d+)/images/edit/$',
        login_required(WallImagesListEditView.as_view()),
        name='walls_images_list_edit'
    ),
    url(r'^(?P<wall_pk>\d+)/images/(?P<pk>\d+)/$',
        WallImagesDetailView.as_view(),
        name='walls_images_detail'
    ),
    url(r'^(?P<wall_pk>\d+)/images/(?P<pk>\d+)/edit/$',
        login_required(WallImagesEditView.as_view()),
        name='walls_images_edit'
    ),
    url(r'^(?P<wall_pk>\d+)/images/(?P<pk>\d+)/delete/$',
        login_required(WallImagesDeleteView.as_view()),
        name='walls_images_delete'
    ),
    url(r'^(?P<wall_pk>\d+)/images/add/$',
        login_required(WallImagesAddView.as_view()),
        name='walls_images_add'
    ),

    url(r'^bbox.json/$',
        'walls.views.bbox',
        name='walls_bbox'
    ),
)

walls/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch.dispatcher import receiver

class Timestamps(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(null=True, blank=True, default=None)

@receiver(pre_save, sender=Timestamps, dispatch_uid="Timestamp_connector")
def paranoid(sender, **kwargs):
    import datetime
    sender.deleted_at = datetime.datetime.now()

class Location(models.Model):
    lat = models.FloatField()
    lon = models.FloatField()

class Ban(models.Model):
    approved_at = models.DateTimeField(null=True, blank=True)
    banned_at = models.DateTimeField(null=True, blank=True)

# Create your models here.
class Wall(Timestamps, Location, Ban):
    reported_by = models.ForeignKey(User)
    address = models.CharField(max_length=250)

    class Meta:
        abstract = True

class PaidWall(Wall):
    PERIOD_CHOICES = (
        (1, "day",),
        (2, "month",),
    )
    price = models.IntegerField()
    period = models.PositiveIntegerField(choices=PERIOD_CHOICES)

class FreeWall(Wall):
    pass

walls/models/comments.py
from django.contrib.auth.models import User
from django.db import models
from util import Timestamps, Paranoid, Ban
from walls import Wall

class PublicManager(models.Manager):
    def get_query_set(self):
        return super(PublicManager, self).get_query_set().filter(is_public = True)

class PrivateManager(models.Manager):
    def get_query_set(self):
        return super(PrivateManager, self).get_query_set().filter(is_public = False)

class WallComment(Timestamps, Paranoid, Ban):
    author = models.ForeignKey(User, editable=False)
    wall = models.ForeignKey(Wall, editable=False)

    ip = models.IPAddressField(blank=True, null=True, editable=False)
    comment = models.TextField()

    is_public = models.BooleanField(default=True)

    class Meta:
        app_label = 'walls'
        ordering = ['created_at']

    # Managers
    objects = models.Manager()
    public = PublicManager()
    private = PrivateManager()

    # Utility methods
    def __unicode__(self):
        return self.comment

    def can_edit(self, user):
        return self.author == user

    def can_delete(self, user):
        return self.author == user

walls/models/geo.py
from django.contrib.gis.db import models as geomodels

class Location(geomodels.Model):
    # GeoDjango fields
    location = geomodels.PointField()

    objects = geomodels.GeoManager()

    class Meta:
        abstract = True

walls/forms.py
from django import forms
from django.contrib.gis import forms as geoforms
from django.utils.translation import ugettext as _
from mapper.widgets import GoogleMapPickLocationWidget
from walls.models import Wall, WallComment, WallImage

class WallForm(geoforms.ModelForm):
    class Meta:
        model = Wall

        widgets = {
            'location': GoogleMapPickLocationWidget(),
        }

class WallCommentForm(forms.ModelForm):
    honeypot = forms.CharField(required=False,
                               label=_('If you enter anything in this field '\
                                       'your comment will be treated as spam'))

    def clean_honeypot(self):
        """Check that nothing's been entered into the honeypot."""
        value = self.cleaned_data["honeypot"]
        if value:
            raise forms.ValidationError(self.fields["honeypot"].label)
        return value

    class Meta:
        model = WallComment

        fields = ('comment',)
        widgets = {
            'comment': forms.Textarea({
                'class': 'span-23'
            })
        }

class WallImageForm(forms.ModelForm):
    class Meta:
        model = WallImage

        fields = ('image', 'title', 'description')

walls/views.py
# Create your views here.
from django.contrib import messages
from django.contrib.gis.geos import Polygon
from django.core.exceptions import ImproperlyConfigured
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.utils.translation import ugettext as _
from django.views.generic.detail import   DetailView
from walls.forms import WallForm, WallCommentForm, WallImageForm
from walls.models import Wall, WallComment, WallImage

class AddWallView(CreateView):
    model = Wall
    form_class = WallForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.reported_by = self.request.user
        self.object.save()
        messages.success(
            self.request,
            _('Your wall is saved. It will be placed on map after moderation.')
        )
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        messages.error(self.request, _('Wall is not saved'))
        return super(AddWallView, self).form_invalid(form)


class EditWallView(UpdateView):
    form_class = WallForm

    def get_queryset(self):
        return Wall.objects.all() |\
               Wall.all_walls.filter(reported_by=self.request.user)

    def get_object(self, queryset=None):
        wall = super(EditWallView, self).get_object(queryset)
        if not wall.can_edit(self.request.user):
            raise Http404
        return wall

    def form_valid(self, form):
        messages.success(self.request, _('Wall is updated'))
        return super(EditWallView, self).form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, _('Wall is not updated'))
        return super(EditWallView, self).form_invalid(form)


class DeleteWallView(DeleteView):
    def get_queryset(self):
        return Wall.objects.all() |\
               Wall.all_walls.filter(reported_by=self.request.user)

    def get_object(self, queryset=None):
        wall = super(DeleteWallView, self).get_object(queryset)
        if not wall.can_delete(self.request.user):
            raise Http404
        return wall

    def get_success_url(self):
        return reverse('walls_index')

    def delete(self, request, *args, **kwargs):
        res = super(DeleteWallView, self).delete(request, *args, **kwargs)
        messages.success(request, _('Wall deleted'))
        return res


class MyWallsListView(ListView):
    template_name = 'walls/my_wall_list.html'
    
    def get_queryset(self):
        return Wall.all_walls.filter(reported_by=self.request.user)


class CommentedDetailView(DetailView):
    comment_form_class = None
    comment_model = None
    comment_queryset = None
    comment_target_field_name = 'target'
    success_url = None

    def get_comment_form_class(self):
        return self.comment_form_class

    def get_comment_form(self, form_class):
        if self.request.method in ('POST', 'PUT',):
            return form_class(self.request.POST)
        return form_class()

    def get_comment_queryset(self):
        if self.comment_queryset is None:
            if self.comment_model:
                return self.comment_model._default_manager.all()
            else:
                raise ImproperlyConfigured()
        return self.comment_queryset._clone()

    def get_context_data(self, **kwargs):
        context = super(CommentedDetailView, self).get_context_data(**kwargs)
        context.update({
            'comments': self.get_comment_queryset().filter(**{
                self.comment_target_field_name: self.object,
                }),
            })
        return context

    def get_success_url(self):
        if not self.success_url:
            raise ImproperlyConfigured()
        return self.success_url

    def form_save(self, form):
        raise NotImplementedError

    def form_valid(self, form):
        self.form_save(form)
        messages.success(self.request, _('Your comment is posted'))
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        messages.error(self.request, _('Your comment was not posted'))
        return self._render_with_form(form)

    def get(self, request, **kwargs):
        form_class = self.get_comment_form_class()
        return self._render_with_form(self.get_comment_form(form_class))

    def post(self, request, *args, **kwargs):
        form_class = self.get_comment_form_class()
        comment_form = self.get_comment_form(form_class)
        if comment_form.is_valid():
            return self.form_valid(comment_form)
        else:
            return self.form_invalid(comment_form)

    def put(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def _render_with_form(self, form):
        self.object = self.get_object()
        return self.render_to_response(
            self.get_context_data(
                object=self.object,
                comment_form=form
            )
        )


class CommentedWallDetailView(CommentedDetailView):
    comment_model = WallComment
    comment_form_class = WallCommentForm
    comment_target_field_name = 'wall'

    def get_queryset(self):
        qs = Wall.objects.all()
        if self.request.user.is_authenticated():
            qs |= Wall.all_walls.filter(reported_by=self.request.user)
        return qs


    def get_success_url(self):
        return reverse('walls_detail', args=[self.object.pk, ])

    def form_save(self, form):
        self.object = self.get_object()
        comment = form.save(commit=False)
        comment.author = self.request.user
        comment.wall = self.object
        comment.ip = self.request.META.get("REMOTE_ADDR", None)
        comment.save()


def bbox(request):
    from django.utils import simplejson

    if request.is_ajax():
        if request.method == 'POST':
            # Process JSON with bbox
            json_data = simplejson.loads(request.raw_post_data)
            try:
                sw_lat = float(json_data['sw']['lat'])
                sw_lng = float(json_data['sw']['lng'])

                ne_lat = float(json_data['ne']['lat'])
                ne_lng = float(json_data['ne']['lng'])
            except (ValueError, KeyError):
                raise Http404

            # Create bbox
            bbox_coords = [
                (sw_lat, sw_lng),
                (sw_lat, ne_lng),
                (ne_lat, ne_lng),
                (ne_lat, sw_lng),
                (sw_lat, sw_lng),
            ]
            bbox_polygon = Polygon(bbox_coords)

            # Process walls limit number
            try:
                num = int(json_data.get('num', 2))
            except ValueError:
                num = 2

            wall_type = json_data.get('wall_type')
            if (wall_type and
                not (isinstance(wall_type, (list, tuple))
                     or getattr(wall_type, '__iter__', False))):
                wall_type = [wall_type]

            qs = Wall.objects.none()

            if 'free' in wall_type:
                qs |= Wall.free.all()
            if 'paid' in wall_type:
                qs |= Wall.paid.all()

            # Get walls in bbox
            walls = qs.filter(location__contained=bbox_polygon)[:num]

            # Assemble walls list
            markers = [{
                'lat': wall.location.x,
                'lng': wall.location.y,
                'title': unicode(wall),
                'is_paid': wall.is_paid(),
                'info': wall.description,
                'url': wall.get_absolute_url(),
                'link_title': _('Details')
            } for wall in walls]

            return HttpResponse(simplejson.dumps(markers),
                                mimetype="application/json; charset=utf-8")
    raise Http404


class WallImagesMixin(object):
    """
    Provides common methods for nested WallImage objects
    """
    model = WallImage
    form_class = WallImageForm

    # regulates adding current user's walls to queryset if they are not approved
    allow_self_walls = False
    # current wall cache
    wall = None

    def get_queryset(self):
        """
        Adds current wall to cache (self.wall) before return queryset
        :return: Current wall's images queryset
        """
        self._get_wall()
        return self.wall.wallimage_set.all()

    def _get_wall(self, force=False):
        """
        Gets Wall object by wall_pk parameter
        :param force: Not to check if self.wall already exists
        :raise: Http404 if wall_pk corresponds to missing wall
        """
        if not self.wall or force:
            wall_pk = self.kwargs['wall_pk']
            qs = Wall.objects.all()
            if self.allow_self_walls:
                qs |= Wall.all_walls.filter(reported_by=self.request.user)
            try:
                self.wall = qs.get(pk=wall_pk)
            except Wall.DoesNotExist:
                raise Http404

    def _assert_can_edit_wall(self, wall=None):
        """
        Checks if current user can edit wall
        :param wall: Wall to check against instead of cached wall
        :raise: Http404 if user can't edit wall
        """
        if not wall:
            self._get_wall()
            wall = self.wall
        if not wall.can_edit(self.request.user):
            raise Http404


class WallImagesListView(WallImagesMixin, ListView):
    def get_context_data(self, **kwargs):
        context = super(WallImagesListView, self).get_context_data(**kwargs)
        context.update({
            'wall_pk': self.kwargs['wall_pk'],
            })
        return context


class WallImagesListEditView(WallImagesListView):
    template_name = 'walls/wallimage_list_edit.html'
    allow_self_walls = True

    def get_queryset(self):
        self._assert_can_edit_wall()
        return super(WallImagesListEditView, self).get_queryset()

templates/walls/_comment_form.html
{% load url from future %}
{% load i18n %}

{% if user.is_authenticated %}
  <form action="" method="post">
    {% csrf_token %}

    {% for field in comment_form %}
      {% if field.is_hidden %}
        {{ field }}
      {% else %}
        {% if field.name == 'honeypot' %}
          {% if field.errors %}{{ field.errors }}{% endif %}
          <div style="display: none;">
            {{ field.label_tag }} {{ field }}
          </div>
        {% else %}
          <div class="field span-24 last {% if field.errors %}error{% endif %}">
            {% if field.errors %}
              <div class="input_errors_top align-left span-24 last">
                {{ field.errors }}
              </div>
            {% endif %}
            <div class="label align-right span-24 last">
              {{ field.label_tag }}
            </div>
            <div class="field-info align-left span-24 last">
              {{ field.help_text }}
            </div>
            <div class="input align-left span-24 last">
              {{ field }}
            </div>
          </div>
        {% endif %}
      {% endif %}
    {% endfor %}

    <input type="submit" value="{% trans 'Post' %}" />
  </form>
{% else %}
  <a href="{% url 'auth_login' %}?next={{ request.get_full_path }}">{% trans 'Log in' %}</a>
  {% trans 'to add a comment' %}
{% endif %}

templates/walls/_comment_list.html
{% load i18n %}
{% load url from future %}

{% if comments %}
  <ul class="comments">
    {% for comment in comments %}
      <li class="span-24 last">
        <div class="span-4">
          <div class="span-4 last">
            <a href="{% url 'profiles_profile_detail' comment.author %}">
              {{ comment.author }}
            </a>
          </div>
          <div class="span-4 last">
            {{ comment.created_at }}
          </div>
        </div>
        <div class="span-20 last">
          {{ comment }}
        </div>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <div class="quiet">
    {% trans 'There is no comments' %}
  </div>
{% endif %}

templates/walls/_wallimage_gallery.html
{% load url from future %}
{% load thumbnail %}

{% if object.wallimage_set %}
  <div id="wall_images" class="span-24 last">
    {% for wall_image in object.wallimage_set.all %}
      {% thumbnail wall_image.image "100x100" crop="center" as im %}
        <a href="{% url 'walls_images_detail' object.pk wall_image.pk %}">
          <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"/>
        </a>
      {% endthumbnail %}
    {% endfor %}
  </div>
{% endif %}

templates/walls/_wallimage_miniature.html
{% load thumbnail %}

{% thumbnail object.image "100x100" crop="center" as im %}
  <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"/>
{% endthumbnail %}

templates/walls/base.html
{% extends 'base.html' %}
{% load i18n menu %}

{% block head %}
  {{ block.super }}
  
  {% include 'inc/_google_maps_api.html' %}
{% endblock %}

templates/walls/my_wall_list.html
{% extends 'walls/base.html' %}
{% load url from future %}
{% load i18n thumbnail %}

{% block content %}
  <div id="object_controls" class="object_controls span-24 last">
    <ul class="menu horizontal">
      <li>
        <a href="{% url 'profiles_profile_detail' user %}">
          {% trans 'Back to profile' %}
        </a>
      </li>
    </ul>
  </div>

  <div id="wall_list" class="span-24 last">
    {% if object_list %}
      <ul>
        {% for object in object_list %}
          <li class="wall_item">
            <a href="{% url 'walls_detail' object.pk %}">
              {{ object }}
            </a>
            {% if object.wallimage_set %}
              <div>
                {% for wall_image in object.wallimage_set.all %}
                  {% thumbnail wall_image.image "50x50" crop="center" as im %}
                    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"/>
                  {% endthumbnail %}
                {% endfor %}
              </div>
            {% endif %}
          </li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>
{% endblock %}

templates/walls/wall_confirm_delete.html
{% extends 'walls/base.html' %}
{% load i18n %}
{% load url from future %}

{% block content %}
  <div id="object_controls" class="object_controls span-24 last">
    <ul class="menu horizontal">
      <li>
        <a href="{% url 'walls_detail' object.pk %}">
          {% trans 'Back to wall' %}
        </a>
      </li>
    </ul>
  </div>

  <h1>{{ object }}</h1>
  {% include 'walls/_wallimage_gallery.html' %}
  <h1>{% trans 'Would you like to delete it?' %}</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="{% trans 'Yes' %}">
    <a href="{% url 'walls_detail' object.pk %}">{% trans 'No' %}</a>
  </form>
{% endblock %}

templates/walls/wall_detail.html
{% extends 'walls/base.html' %}
{% load url from future %}
{% load i18n map_view safe_output models %}

{% block content %}
  <div id="wall_detail" class="span-24 last">
    <div id="object_controls" class="object_controls span-24 last">
      <ul class="menu horizontal">
        {% ifcan request.user 'edit' object %}
          <li>
            <a href="{% url 'walls_edit' object.pk %}">{% trans 'Edit' %}</a>
          </li>
          <li>
            <a href="{% url 'walls_images_list_edit' object.pk %}">
              {% trans 'Edit images' %}
            </a>
          </li>
        {% endifcan %}
        {% ifcan request.user 'delete' object %}
          <li>
            <a href="{% url 'walls_delete' object.pk %}">{% trans 'Delete' %}</a>
          </li>
        {% endifcan %}
      </ul>
    </div>
    <div id="wall_info" class="span-10">
      <div class="object_field">
        <div class="object_field_title">{% trans 'Address' %}</div>
        {{ object.address }}
      </div>
      <div class="object_field">
        <div class="object_field_title">{% trans 'Price' %}</div>

        {% if object.is_paid %}
          {{ object.price }} / {{ object.get_period_display }}
        {% else %}
          {% trans 'Free' %}
        {% endif %}
      </div>
      <div class="object_field">
        <div class="object_field_title">{% trans 'Description' %}</div>
        {% safe_html object.description %}
      </div>
    </div>

    <div id="wall_location" class="object_field span-14 last">
      <div class="object_field_title">{% trans 'Location' %}</div>
      {% map_view wall '10' '500px' '500px' %}
      <h5>
        <span>{% trans 'I am lost!' %}</span>&nbsp;
        <span id='locate_marker_control'>{% trans 'locate wall' %}</span>
      </h5>
    </div>

    {% include 'walls/_wallimage_gallery.html' %}

  </div>

  <div id="comments_container" class="comments_container span-24 last">
    <div id="comments_list" class="comments_list span-24 last">
      {% include 'walls/_comment_list.html' %}
    </div>
    <div id="comments_form" class="comments_form span-24 last">
      {% include 'walls/_comment_form.html' %}
    </div>
  </div>
{% endblock %}

templates/walls/wall_form.html
{% extends 'walls/base.html' %}
{% load url from future %}
{% load i18n thumbnail form %}

{% block head %}
  {{ block.super }}
  
  {{ form.media }}
{% endblock %}

{% block content %}
  {% if form.instance.pk %}
    <div id="object_controls" class="object_controls span-24 last">
      <ul class="menu horizontal">
        <li>
          <a href="{% url 'walls_detail' form.instance.pk %}">
            {% trans 'Back to wall' %}
          </a>
        </li>
        <li>
          <a href="{% url 'walls_images_list_edit' object.pk %}">
            {% trans 'Edit images' %}
          </a>
        </li>
      </ul>
    </div>

    {% if form.instance.wallimage_set %}
      <div class="span-24 last">
        {% for wall_image in form.instance.wallimage_set.all %}
          {% thumbnail wall_image.image "100x100" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {% endthumbnail %}
        {% endfor %}
      </div>
    {% endif %}
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <div class="form span-24 last">
      <div class="non_field_errors span-24 last">
        {{ form.non_field_errors }}
      </div>
      {% for field in form %}
        <div class="field span-24 last {% if field.errors %}error{% endif %}">
          {% if field.errors %}
            <div class="input_errors_top align-left span-24 last">
              {{ field.errors }}
            </div>
          {% endif %}
          <div class="label align-right span-24 last">
            {{ field.label_tag }}
          </div>
          <div class="field-info align-left span-24 last">
            {{ field.help_text }}
          </div>
          <div class="input align-left span-24 last">
            {{ field }}
          </div>
        </div>
      {% endfor %}
      <div class="field submit span-24 last">
        <input type="submit" value="{% trans 'Save' %}"/>
      </div>
    </div>
  </form>
{% endblock %}

templates/walls/wallimage_confirm_delete.html
{% extends 'walls/base.html' %}
{% load i18n %}
{% load url from future %}

{% block content %}
  <h2>{{ object }}</h2>

  <a href="{{ object.image.url }}">
    {% include 'walls/_wallimage_miniature.html' %}
  </a>

  <h1>{% trans 'Would you like to delete it?' %}</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="{% trans 'Yes' %}">
    <a href="{% url 'walls_images_detail' object.wall_id object.pk %}">
      {% trans 'No' %}
    </a>
  </form>
{% endblock %}

templates/walls/wallimage_detail.html
{% extends 'walls/base.html' %}
{% load url from future %}
{% load i18n thumbnail models %}

{% block content %}
  <div id="object_controls" class="object_controls span-24 last">
    <ul class="menu horizontal">
      <li>
        <a href="{% url 'walls_detail' object.wall_id %}">
          {% trans 'Back to wall' %}
        </a>
      </li>
      {% ifcan request.user 'edit' object.wall %}
        <li>
          <a href="{% url 'walls_images_edit' object.wall_id object.pk %}">
            {% trans 'Edit' %}
          </a>
        </li>
        <li>
          <a href="{% url 'walls_images_delete' object.wall_id object.pk %}">
            {% trans 'Delete' %}
          </a>
        </li>
      {% endifcan %}
    </ul>
  </div>

  <h2>{{ object }}</h2>
  
  {% thumbnail object.image "300x300" crop="center" as im %}
    <a href="{{ object.image.url }}">
      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}"/>
    </a>
  {% endthumbnail %}

  <div class="span-24 last">
    {{ object.description }}
  </div>

{% endblock %}

templates/walls/wallimage_form.html
{% extends 'walls/base.html' %}
{% load url from future %}
{% load i18n %}

{% block content %}
  <div id="object_controls" class="object_controls span-24 last">
    <ul class="menu horizontal">
      <li>
        <a href="{% url 'walls_images_list_edit' wall_pk %}">
          {% trans 'Back to wall images' %}
        </a>
      </li>

      {% if form.instance.pk %}
        <li>
          <a href="{% url 'walls_images_detail' wall_pk form.instance.pk %}">
            {% trans 'Show image' %}
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
  
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="form span-24 last">
      <div class="non_field_errors span-24 last">
        {{ form.non_field_errors }}
      </div>
      {% for field in form %}
        {% if field.is_hidden %}
          {{ field }}
        {% else %}
          <div class="field span-24 last {% if field.errors %}error{% endif %}">
            {% if field.errors %}
              <div class="input_errors_top align-left span-24 last">
                {{ field.errors }}
              </div>
            {% endif %}
            <div class="label align-right span-24 last">
              {{ field.label_tag }}
            </div>
            <div class="field-info align-left span-24 last">
              {{ field.help_text }}
            </div>
            <div class="input align-left span-24 last">
              {{ field }}
            </div>
          </div>
        {% endif %}
      {% endfor %}
      <div class="field submit span-24 last">
        <input type="submit" value="{% trans 'Save' %}"/>
      </div>
    </div>
  </form>
{% endblock %}